#!/usr/bin/env bash

DIR=`dirname "$0"`
DIR=`cd .; pwd`
ASSEMBLY="${DIR}/target/spark-XXX-assembly-1.0-SNAPSHOT.jar"

# 1. determine READR_CONF_DIR

# 1.1 check to see if the conf dir is given as an optional argument
if [ $# -gt 1 ]
then
    if [ "--config" = "$1" ]
          then
              shift
              confdir=$1
              shift
              READR_CONF_DIR=$confdir
    fi
fi

# 1.2 check if there is an environment variable

if [ "$READR_CONF_DIR" = "" ]; then
  READR_CONF_DIR=$READR_CONF_DIR
fi

# 1.3 try to follow relative path from current directory
if [ "$READR_CONF_DIR" = "" ]; then
  RELDIR="${DIR}/../../conf"
  if [ -e $RELDIR ]; then
     READR_CONF_DIR=$RELDIR;
  fi
fi

# 1.4 throw error
if [ "$READR_CONF_DIR" = "" ]; then
  echo "No READR_CONF_DIR set. Set as environment variable or on command line using '--config'."
  exit 1
fi

# 1.5 export
export READR_CONF_DIR=${READR_CONF_DIR}

# 2. run the jar
java -jar -Xmx2048m "${ASSEMBLY}" $@
